app = "mjschock"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  FLET_APP_STORAGE_DATA = "/app/storage/data"
  FLET_SESSION_TIMEOUT = "60"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    soft_limit = 200
    hard_limit = 250
